### ISSUE TITLE
Should timeline show last 24 hours or current day's activity

### ISSUE THREAD

**Issue by keitharm** [gabriel-discord/gabriel-ui#28]
Should the timeline only consist of today's activity or should it show the last 24 hours?

![image](https://user-images.githubusercontent.com/919806/100909474-66d47000-3492-11eb-8f52-adc52e4d42df.png)

![image](https://user-images.githubusercontent.com/919806/100909661-a00ce000-3492-11eb-87e7-3322cca2e796.png)

**Comment by jfwu90** [comment]
I prefer last 24 hours since people have the tendency to play past midnight. However, it's possible to add an option so the user can switch between both. If this is desirable, create an enhancement issue.
