### ISSUE TITLE
Combine game sessions of the same game that are within ~10 minutes of each other

### ISSUE THREAD

**Issue by keitharm** [gabriel-discord/gabriel-ui#37]
Some games such as Call of Duty and Battlefield sometimes have a menu update in the beginning that requires the game to be restarted.

Individual game sessions (of the same game) that are started/ended within ~10 minutes of each other should be combined as one.

**Comment by jfwu90** [comment]
@keitharm is this necessary? I think it'd be useful to see the timeline and recognize at what points the game crashed.
